### ISSUE TITLE
Add text to footer

### ISSUE THREAD

**Issue by ODILMichelle** [open-innovations/leeds-2023#124]
Request from L23. 

Can we add a disclaimer to the footer, something along the lines of 

"The data and visualisations displayed on this site are drawn from a variety of systems run by LEEDS 2023. They are indicative figures only, published and visualised to support operational decision-making by the team as well ensuring LEEDS 2023 is being transparent about their work."

**Comment by gilesdring** [comment]
Have amended as follows:



![Image](https://user-images.githubusercontent.com/1731108/234358796-75b04658-fb39-4d96-af7e-c43edcd9e514.png)

**Comment by gilesdring** [comment]
Needed to discuss your intent about that. I have many questions. Questions such as: Do you think there should be a different footer on each page? Or, would a link from home page to home page be OK? Is the "extra text" on the main page in the footer or in the home page? If the latter, where? I did ponder if we ought to have an "about this data" page, instead of the home page.

As it was, actioned the initial ask which seemed quite clear, with a view to discussing the less well defined.

**Comment by gilesdring** [comment]
Or is the main page text as it stands sufficient...

**Comment by ODILMichelle** [comment]
:) Let's pick this up on the morrow.
