### ISSUE TITLE
Fix data pipeline job failure

### ISSUE THREAD

**Issue by taz-chiles** [open-innovations/leeds-2023#135]
Job failing with error: 

![Image](https://user-images.githubusercontent.com/97239140/235916777-273b4766-9a49-45f5-a217-ccb4d8915f27.png)

**Comment by gilesdring** [comment]
Job fixed. I've captured the assertion rather than allowing it to throw issues and fail the entire pipeline.

There's now a log in https://github.com/open-innovations/leeds-2023/blob/main/working/log/schools_prepare.log which captures these problems.

@ODILMichelle Per chat yesterday, there is at least one line in the schools extract that has multiple schools. We may have some problems in geography counts, which L23 can fix by doing what they did before.
