### ISSUE TITLE
Remove schools from community engagement

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-2023#22]
Create cut of data excluding schools engagement, and present separately.

Tabbed view

**Comment by gilesdring** [comment]
Could you review https://data.leeds2023.co.uk/dashboard/community/ @ODILMichelle

**Comment by ODILMichelle** [comment]
Love that when you have no schools engagement all schools related figures are removed e.g. in the top visualisation, in the tables, and in the ward focussed initiatives. 

Not completely sure that the text change alone makes it obvious what has happened. I don't know if there is a way to e.g. have a toggle within the map itself that allows you to turn on/off schools engagement. Alternatively, if that takes significant time we might want to change the way the second paragraph is presented (line starting "This version of the dashboard includes schools data.."

This might be making it bold, it might be adding a box and colour to that section to make it stand out - otherwise given the same content at the top of the page it is easy for it to blur into one. 

We may also want to change the names of the hexmaps in each instance e.g. 'Count of activities by residents in each ward' and 'Count of activities by residents in each ward, including schools engagement' (or similar).

**Comment by ODILMichelle** [comment]
Was just mulling, another way of signally clearly that something has changed might be to change the colour pallet of the hexmap itself - for instance to pink which we use elsewhere.

**Comment by gilesdring** [comment]
I'll change the colour and chart titles. Think the text might be useful as well.

**Comment by ODILMichelle** [comment]
Thanks for this, will discuss with Fiona today

**Comment by ODILMichelle** [comment]
Fiona is happy with this. A few other questions about layout and styling but will be added as separate tickets
